OKTA-473084: modify the details scripts to add flows data to the workflow json files
okta/workflows-templates pull request #141
Opened 2022-02-23 20:10 UTC by hossammourad-okta

https://oktainc.atlassian.net/browse/OKTA-473084

2022-02-23 20:29 UTC, hossammourad-okta commented
@shauntarves-okta please give this is a review before I go ahead and modify the `workflow.json` files using the modifier script.

2022-02-25 18:56 UTC, shauntarves-okta requested changes

2022-02-25 18:56 UTC, shauntarves-okta commented on scripts/json-details-scripts/details_validator.js
> +  if (workflowName === ".DS_Store") return;
This is unfortunate, but I think a better check would be to either limit `workflows` to only be directories or check if the current item is a directory, rather than playing whack-a-mole with [potentially] other hidden files

2022-02-25 19:05 UTC, hossammourad-okta commented on scripts/json-details-scripts/details_validator.js
> +  if (workflowName === ".DS_Store") return;
Great catch. Done.

2022-02-25 19:13 UTC, shauntarves-okta approved these changes

2022-02-25 19:46 UTC, shauntarves-okta approved these changes

2022-02-25 19:48 UTC, merged