OKTA-480004: update readme with info about screenshots
okta/workflows-templates pull request #145
Opened 2022-03-21 18:01 UTC by hossammourad-okta

https://oktainc.atlassian.net/browse/OKTA-480004
Adding documentation about workflows screenshots.

Changes are welcome if you think something should be phrased differently.

2022-03-22 18:56 UTC, shauntarves-okta requested changes

2022-03-22 18:56 UTC, shauntarves-okta commented on README.md
> +The screenshot should cover the full flow, not only parts of it, also it should be in high resolution.
"...should cover the full flow, plus the beginning and ending cards" or similar to indicate we want to capture the "placeholder" cards

2022-03-30 21:38 UTC, hossammourad-okta commented
@shauntarves-okta I added the tutorial to the repo as a readme file because Confluence pages are private and having the tutorial over there is worthless. I added the tutorial readme link to the readme of the repo as well in the top.

2022-03-31 14:33 UTC, shauntarves-okta approved these changes
This tutorial is a really, really great addition. Good catch on moving it into this repo vice having it in the wiki!

2022-04-01 17:12 UTC, merged