WIP
okta/workflows-templates pull request #146
Opened 2022-03-21 18:55 UTC by hossammourad-okta

2022-03-30 19:22 UTC, hossammourad-okta commented on scripts/json-details-scripts/details_validator.js
> +    const jsonDetailsWithoutScreenshots = cloneDeep(detailsInJSON);
This is a bug that hasn't been caught beforehand. Using the spread operators executes a shallow clone, which is problematic in this case because `detailsInJSON` is a nested object.

2022-03-30 19:23 UTC, hossammourad-okta commented on scripts/json-details-scripts/details_modifier.js
> +    jsonContent.details = merge(jsonContent.details, generatedDetails);
This merge is required (instead of a straight assignment) to maintain `screenshotURL` values in `jsonContent`.

2022-04-01 13:19 UTC, shauntarves-okta requested changes

2022-04-01 13:19 UTC, shauntarves-okta commented on package.json
> +    "lodash": "^4.17.21"
I think the methods you are using from lodash are pretty simple to replicate with native code. See below

2022-04-01 13:19 UTC, shauntarves-okta commented on scripts/json-details-scripts/details_modifier.js
> +    jsonContent.details = merge(jsonContent.details, generatedDetails);
prefer: native `Object.assign`

Unless I'm missing a subtlety here, wouldn't we just be able to do `Object.assign(jsonContent.details, generatedDetails)`? We wouldn't even need to do any kind of assignment to a new object since `Object.assign` directly mutates the first argument

2022-04-01 13:19 UTC, shauntarves-okta commented on scripts/json-details-scripts/details_validator.js
> +    const jsonDetailsWithoutScreenshots = cloneDeep(detailsInJSON);
prefer: `Object.assign({}, detailsInJSON)`

This should create a new object `{}` and assign all of the properties of `detailsInJSON` to it.

2022-04-01 14:12 UTC, hossammourad-okta commented on scripts/json-details-scripts/details_validator.js
> +    const jsonDetailsWithoutScreenshots = cloneDeep(detailsInJSON);
`Object.assign` creates a shallow copy of an object, in this case I'm deleting certain fields in nested object in the next lines, the field will get deleted from the original object if I create a shallow object.

![image](https://user-images.githubusercontent.com/97123127/161280628-3e9b9c2a-466b-4a58-aeb8-dfd1039adbd7.png)

2022-04-01 14:23 UTC, hossammourad-okta commented on scripts/json-details-scripts/details_modifier.js
> +    jsonContent.details = merge(jsonContent.details, generatedDetails);
I think what you're missing here is that `jsonContent.details` contains 1 extra field (`screenshotURL` - potentially more in the future) that doesn't exist in `generatedDetails`.

if I used that suggestion, whatever the content of the `generatedDetails` object will overwrite the entirety of the `jsonContent.details` object. That's not what we want, we want only to overwrite the fields that are common between both objects.

2022-04-01 15:42 UTC, shauntarves-okta commented on scripts/json-details-scripts/details_validator.js
> +    const jsonDetailsWithoutScreenshots = cloneDeep(detailsInJSON);
Okay, didn't realize you were deleting fields. 👍

2022-04-01 15:45 UTC, shauntarves-okta commented on scripts/json-details-scripts/details_modifier.js
> +    jsonContent.details = merge(jsonContent.details, generatedDetails);
Okay, understood. Didn't realize the incoming object was missing all the data 👍

2022-04-01 15:45 UTC, shauntarves-okta approved these changes

2022-04-01 16:16 UTC, merged