OKTA-467419: generate screenshots for templates + populate screenshot url field
okta/workflows-templates pull request #147
Opened 2022-03-22 13:56 UTC by hossammourad-okta

This PR is a retry of https://github.com/okta/workflows-templates/pull/134

This PR does the following:
1. Generate screenshots for the workflows and uses a hash (instead of the FLO name) for the file name. The hash used for file names depends on the screenshot content
2. Inject the corresponding screenshot URL in each `workflow.json` file.

### Testing
- [ ] Verify there is a screenshot for each FLO
- [ ] Verify the content of the screenshots
- [ ] Verify the URLs in the `workflow.json` files are reachable publicly

Sorry @charleschan-okta for the rework here. I tried to find a way to avoid testing rework but I couldn't.

### Notes

#### This is the mechanism I used to hash the content of screenshot files:

```js
function generateFileHash (fileBuffer) {
  const crypto = require("crypto");
  return crypto.createHash('sha256').update(fileBuffer).digest('base64url');
};
```

#### I used this NodeJS script for my own testing purposes to verify that the screenshot URLs are reachable publicly. Feel free to reuse it if you find it fit:
```js
const fs =  require("fs");
const fetch = require("node-fetch");

const path = `${WORKFLOWS_TEMPLATES_REPO_ABSOLUTE_PATH}/workflows`;

const screenshots = [];

fs.readdirSync(path).forEach(workflow => {
  if (!fs.lstatSync(`${path}/${workflow}`).isDirectory()) return;

  JSON.parse(fs.readFileSync(`${path}/${workflow}/workflow.json`).toString()).details.flos.forEach(flo => {
    screenshots.push(flo.screenshotURL);
  });
});

screenshots.forEach(screenshot => {
  fetch(screenshot).then(data => {
    if (!data.ok) {
      throw new Error(`The "${screenshot}" screenshot link is not valid`);
    }
  }).catch(error => {
    console.log(`The "${screenshot}" screenshot link is not valid`);
    console.error(error);
  });
});
```

2022-03-22 14:59 UTC, hossammourad-okta commented on scripts/json-details-scripts/utils.js
> -        screenshotURL: "" // TODO: replace with the actual S3 URL
This field should have never been part of `getDetailsFromFlopack` because conceptually screenshots weren't ever part of the flopack. This doesn't mean that screenshots won't be validated, it's coming in a in-progress PR https://github.com/okta/workflows-templates/pull/146

2022-03-22 18:52 UTC, shauntarves-okta requested changes
I can't seem to add comments to the photo files, but there are a few broken ones and a few that look like the mouse happened to be in the wrong spot so it activated a tooltip or the xray feature in IDE.

These are broken/malformed in one way or another:

- `workflows/form_submission_to_workflows_api_endpoint/resources/CUSCVSAeN6vAXWX0U9ovvBy_x2RGDbgxT8H9YN4jAVw.png`
- `workflows/manage_aws_sso_entitlements/resources/Ax1ygR3LuxtxqO8rlnEI6iuXYNZI1bjAujn1CdRx4EU.png`
- `workflows/manage_aws_sso_entitlements/resources/T4EvZDb_WLGpDgfos01QInxX5g9rsGGJ_0iJpB6gjCI.png`
- `workflows/reassign_files_while_deprovisioning_with_box/resources/gYMRfqyk1kWr7klri-rOQNeb8lN0pTzyrgMVgN6XqtI.png`
- `workflows/remote_sync/resources/u093u5y_wNG5vA_pDnuUVa_CHRlpSaPr_Mm2VVv1WTM.png`
- `workflows/suspicious_activity_event_alerts_pagerduty/resources/t9CLGgSCmJWrkHcwuPJ_I7f6ROq1B7vdg3LFS1oT6G8.png`
- 

These ones, if possible, we should move the cursor offscreen programmatically and regenerate:

- `workflows/access_request_with_slack/resources/06vs4F4lTvB_ZtLnAmX2l7aqmP977Fa-mASSNRl7mjM.png`
- `workflows/access_request_with_slack/resources/apLWhXEAUn4rrfI_bKy_xIrltltSjDllqzpttpENoxM.png`
- `workflows/execute_onpremise_powershell_with_okta_workflows/resources/IgfcCTjI3qpoA9uZ31Bz2zefrwlGxDv113J30kaCQtw.png`

2022-03-22 19:54 UTC, hossammourad-okta commented
@shauntarves-okta where is the cursor in these two screenshots:

```
workflows/access_request_with_slack/resources/apLWhXEAUn4rrfI_bKy_xIrltltSjDllqzpttpENoxM.png
workflows/execute_onpremise_powershell_with_okta_workflows/resources/IgfcCTjI3qpoA9uZ31Bz2zefrwlGxDv113J30kaCQtw.png
```

I can't see it.

2022-03-22 20:05 UTC, shauntarves-okta commented
The "mappings" overlay (the connections between the 2 fields) are an indication that the cursor is positioned on either side of the "connection" (the source or the consumer).

> workflows/access_request_with_slack/resources/apLWhXEAUn4rrfI_bKy_xIrltltSjDllqzpttpENoxM.png
![Screen Shot 2022-03-22 at 3 58 31 PM](https://user-images.githubusercontent.com/89813167/159565617-d6783f65-4a32-479c-8a92-2fecbee15a0a.png)

 > workflows/execute_onpremise_powershell_with_okta_workflows/resources/IgfcCTjI3qpoA9uZ31Bz2zefrwlGxDv113J30kaCQtw.png
![Screen Shot 2022-03-22 at 3 58 48 PM](https://user-images.githubusercontent.com/89813167/159565641-dce18854-4512-4c2a-a5b0-f1ccce4ebabc.png)

If this is difficult to figure out or resolve, you can likely have success just by turning off the mappings.
![Screen Shot 2022-03-22 at 4 04 45 PM](https://user-images.githubusercontent.com/89813167/159566446-e4f6804d-7ecf-4b25-8e6c-39497f8c0401.png)

2022-03-22 20:12 UTC, hossammourad-okta commented
I actually like that the mappings are rendered in screenshots. It explains how powerful a workflow can be by connecting fields. If the mappings are rendered for all workflows (which I think is the case), then I would recommend leaving them.

2022-03-22 20:19 UTC, shauntarves-okta commented
> I actually like that the mappings are rendered in screenshots. It explains how powerful a workflow can be by connecting fields. If the mappings are rendered for all workflows (which I think is the case), then I would recommend leaving them.

They are dynamically rendered when the user hovers over a field that is connected. They only appear in these 2 screenshots because the mouse [likely] happens to be on one of the fields. There is no way to see all connected fields at once in the WAX IDE, but I think that's the scenario you're describing in which they'd be useful. I just don't think we want them visible in 2 of 170 screenshots, because there are definitely connected fields in all the others.

2022-03-22 20:32 UTC, hossammourad-okta commented
Agreed. I thought the mappings are rendered for all. I moved the mouse cursor to `x: 0,y: 0` before taking the screenshots. The issues you mentioned above are fixed now.

2022-03-22 20:51 UTC, shauntarves-okta approved these changes

2022-03-28 14:19 UTC, hossammourad-okta commented
@shauntarves-okta @charleschan-okta According to [this ticket](https://oktainc.atlassian.net/browse/OKTA-482779) and my discussion with Shaun last week, I replaced any instance of "child" with "helper" in this commit https://github.com/okta/workflows-templates/pull/147/commits/78b559f9e3011e17735b26811f3d1d7a2f516cff all across the repo. There should not be any reference to the word "child" in the repo files/folders except URLs.

Can you please confirm these are all the **correct** changes we need to do before I regenerate the screenshots?

2022-03-28 14:47 UTC, shauntarves-okta commented
> Can you please confirm these are all the **correct** changes we need to do before I regenerate the screenshots?

Quick spot check looks good. There are so many references across so many files that describing _what_ you did to make the changes might be more straightforward. I think the biggest potential issue would be if case didn't get matched/replaced properly, but I didn't see any instances of that.

2022-03-28 17:28 UTC, hossammourad-okta commented
@shauntarves-okta @charleschan-okta 

I just discovered that modifying the flopack files only here in this repo is not a viable option. After modifying a `.flopack` file and trying to import them, I get this error:

![image](https://user-images.githubusercontent.com/97123127/160453715-1b26de8f-fe0b-4f28-869b-5318dd46d8e2.png)

Which is thrown by this block from `azuqua-publisher`:

![image](https://user-images.githubusercontent.com/97123127/160453776-16857235-d4a7-4683-94b0-b4f2133aa99d.png)

The "child" to "helper" change is bigger than the scope of FLOs screenshots.

2022-03-28 17:46 UTC, charleschan-okta commented
@viktoriyaabakumova-okta Pl see @hossammourad-okta's comment: apparently modifying a flopack to replace "Child Flow" w/ "Helper Flow" prevent the flopack from being imported:
![image](https://user-images.githubusercontent.com/18430216/160456494-628da094-3e08-4a79-82ef-f43d992ab317.png)

Can we bypass the check or we need to re-generate the flopack?

2022-03-28 17:55 UTC, viktoriyaabakumova-okta commented
If re-exporting the flopack isn't an option, you can change the version in the flopack file to `1.2.0` instead of `1.3.0` to bypass the modified flopack check

2022-03-28 18:11 UTC, charleschan-okta commented
@hossammourad-okta I tried @viktoriyaabakumova-okta's suggestion and it worked:

1. exporting a child flow
2. change all instances of 'Child Flow' to 'Helper Flow', save
3. import the modified .flow file & got the "Flopack has been modified" error
4. change the version from 1.3.0 to 1.2.0, save
5. Able to import & observe the flow is now "Helper Flow
6. This should work for folder also, I suppose

2022-03-29 14:58 UTC, shauntarves-okta commented
@viktoriyaabakumova-okta do you know _why_ the bump to 1.3 bypasses the integrity check?

While this obviously works, it seems less desirable than simply regenerating the hash with the changes. I don't want to have to re-export all the flopacks from scratch, but I'm curious if we can replicate the hashing logic easily. I'll look into this shortly, but if you have any info on the above question, please share!

2022-03-29 15:03 UTC, hossammourad-okta commented on scripts/travis_release.sh
> +        pr_files="$(git diff --name-only --diff-filter=ACMR master..${branch_name} --)"
@shauntarves-okta This change needs reviewing.

1. The old `git diff` command was outputting what's on `master` that is not on the branch, but I believe we want it the other way around. `pr_files` should hold what's on the branch that's not on `master`.
2. The old command (without using `diff-filter`) gives back deleted files which is a behavior we don't want. According to [the documentation of the `diff-filter`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) I added `ACMR` -> A: Added, C: Copied, M: Modified, R: Renamed

2022-03-29 16:11 UTC, hossammourad-okta commented on scripts/travis_release.sh
> +        pr_files="$(git diff --name-only --diff-filter=ACMR ${branch_name}...HEAD --)"
@shauntarves-okta This change needs reviewing.

The old command (without using `diff-filter`) gives back deleted files which is a behavior we don't want. According to [the documentation of the `diff-filter`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) I added `ACMR` -> A: Added, C: Copied, M: Modified, R: Renamed

2022-03-29 23:20 UTC, shauntarves-okta approved these changes

2022-03-31 15:41 UTC, charleschan-okta approved these changes
LGTM 🚀

2022-04-01 16:05 UTC, merged