New Template - Generate Unique username
okta/workflows-templates pull request #22
Opened 2020-09-08 21:10 UTC by arvilnagpal-okta

2020-09-08 21:10 UTC, arvilnagpal-okta commented
@charleschan-okta @uvartak-okta plz review

2020-09-08 22:56 UTC, uvartak-okta approved these changes
⛵

2020-09-09 05:15 UTC, charleschan-okta requested changes
Just some nits & formatting issues.

2020-09-09 05:15 UTC, charleschan-okta commented on workflows/generate_unique_username/readme.md
> +6. If you want to test preferredfirstName and preferredLastname. Make sure those are set as required attributes in Okta. So that when you create a user in the admin console it is populated as a requi
So that when you create a user in the admin console, they are populated as required attributes.

2020-09-09 05:15 UTC, charleschan-okta commented on workflows/generate_unique_username/readme.md
> +4.Click on the first card endpoint settings at the bottom and copy the Invoke URL to the import inline hook endpoint settings in Okta. Check the screenshot below
Need to format 4.Click to align w/ above lists 1, 2, 3

2020-09-09 05:15 UTC, charleschan-okta commented on workflows/generate_unique_username/readme.md
> +8.Go to provisioning tab - to Okta page.
Need to format "8.Go to provisioning tab - to Okta page." to align w/ above lists 1, 2, 3,...6, 7

2020-09-09 18:05 UTC, charleschan-okta approved these changes
The nits & formatting issues will not be fixed for now. Arvil said "going to have docs do a pass on this later this week since it still needs work. think we can ship for now."
🚢

2020-09-09 18:21 UTC, merged