New Template - AD credential delivery
okta/workflows-templates pull request #24
Opened 2020-09-08 21:58 UTC by arvilnagpal-okta

@charleschan-okta @uvartak-okta plz review

2020-09-08 23:31 UTC, charleschan-okta requested changes

2020-09-08 23:31 UTC, charleschan-okta commented on workflows/send_mgr_ad_credentials/workflow.json
> +      "okta"
missing office365mail connector, which is used in the flow

2020-09-08 23:35 UTC, arvilnagpal-okta commented on workflows/send_mgr_ad_credentials/workflow.json
> +      "okta"
good catch

2020-09-08 23:46 UTC, arvilnagpal-okta commented on workflows/send_mgr_ad_credentials/workflow.json
> +      "okta"
done

2020-09-09 01:19 UTC, charleschan-okta approved these changes
LGTM 🚀

2020-09-09 18:22 UTC, merged