[OKTA-819355] feat: add a new template okta_identity_governance_access_certification_camp
okta/workflows-templates pull request #246
Opened 2024-11-27 15:33 UTC by akshayaappaswamy-okta

[OKTA-819355] feat: add a new template okta_identity_governance_access_certification_camp

Jira ticket: https://oktainc.atlassian.net/browse/OKTA-819355

Please review : @runzeng-okta

2024-11-27 23:58 UTC, runzeng-okta requested changes

2024-11-27 23:58 UTC, runzeng-okta commented on workflows/okta_identity_governance_access_certification_camp/workflow.json
> +    "stashCount": 0,
Please remove stashCount because its value is 0. It causes workflows.json CI/CD validation failed.

2024-11-27 23:58 UTC, runzeng-okta commented on workflows/okta_identity_governance_access_certification_camp/resources/000ff8bbc320e9cee4a40a95bb50c0ec1ef9.png
The third card from left - Construct card, you could extend the size of the input fields, so that the full string can be visible. This is just an example, I see many cards in the screenshots can be improved in this way. Please redo the screenshots.
<img width="302" alt="Screenshot 2024-11-27 at 4 54 39 PM" src="https://github.com/user-attachments/assets/60e81417-0737-41b0-8858-67c114bef324">

2024-11-27 23:58 UTC, runzeng-okta commented on workflows/okta_identity_governance_access_certification_camp/workflow.json
> +    "mainFlowsCount": 0
"mainFlowsCount" value is 0, it may cause the CI/CD validation fail. Can you please verify?

2024-11-28 00:00 UTC, runzeng-okta commented
Hi @akshayaappaswamy-okta, please make sure all CI/CD test passed before asking my review, you can see the CI/CD validation above.
<img width="990" alt="Screenshot 2024-11-27 at 4 59 01 PM" src="https://github.com/user-attachments/assets/23e9e86c-1d5d-40c5-b203-3a645bc1fd11">

2024-11-28 03:29 UTC, akshayaappaswamy-okta commented on workflows/okta_identity_governance_access_certification_camp/resources/000ff8bbc320e9cee4a40a95bb50c0ec1ef9.png
Sure, I understand. Will redo them and submit again.

2024-11-28 03:29 UTC, akshayaappaswamy-okta commented on workflows/okta_identity_governance_access_certification_camp/workflow.json
> +    "stashCount": 0,
Yes sure.

2024-11-28 06:51 UTC, closed without merging