New Template - temp group memberships
okta/workflows-templates pull request #25
Opened 2020-09-08 22:09 UTC by arvilnagpal-okta

@uvartak-okta @charleschan-okta plz review

2020-09-08 22:50 UTC, charleschan-okta requested changes
typo: tempory should be: temporary, pl change:
assign_tempory_group_memberships to assign_temporary_group_memberships in the path, as well as in the workflow.json file

2020-09-08 22:50 UTC, charleschan-okta commented on workflows/assign_tempory_group_memberships/workflow.json
> +   "name": "assign_tempory_group_memberships",
typo: tempory should be: temporary

2020-09-08 22:50 UTC, charleschan-okta commented on workflows/assign_tempory_group_memberships/workflow.json
> +         "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/assign_tempory_group_memberships/readme.md"
ditto

2020-09-08 23:16 UTC, arvilnagpal-okta commented on workflows/assign_tempory_group_memberships/workflow.json
> +   "name": "assign_tempory_group_memberships",
done

2020-09-08 23:16 UTC, arvilnagpal-okta commented on workflows/assign_tempory_group_memberships/workflow.json
> +         "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/assign_tempory_group_memberships/readme.md"
done

2020-09-09 01:05 UTC, charleschan-okta commented on workflows/assign_temporary_group_memberships/readme.md
> +    3. Navigate to Workflows Tables, Temporary Groups table. (this table should have been imported with your flow).
![image](https://user-images.githubusercontent.com/18430216/92542505-c574af80-f1fd-11ea-8723-d6772a5ea8f1.png)

2020-09-09 01:16 UTC, charleschan-okta requested changes
Pl fix the list formatting issue also.

2020-09-09 01:53 UTC, arvilnagpal-okta commented
> Pl fix the list formatting issue also.

Sorry, what was this in reference to?

2020-09-09 17:42 UTC, charleschan-okta approved these changes
LGTM 🚀

2020-09-09 18:22 UTC, merged