Davidroossien wt okta 343763
okta/workflows-templates pull request #45
Opened 2020-11-25 00:28 UTC by davidroossien-okta

Note: I had to rename the folder to include underlines, so there are deleted files from contractor-expiry-notice, and only the added files inside contractor_expiry_notice should be reviewed.

2020-11-25 21:57 UTC, charleschan-okta requested changes
1) workflow.json file needs to be updated (using underscore instead of dash for the path)
2) minor typo in readme file
3) u probably want to remove all the files that are still using dash in the path to avoid confusion. If these are merged, they can also show up in the catalog

2020-11-25 21:57 UTC, charleschan-okta commented on workflows/contractor_expiry_notification/readme.md
> +Below is a summary of the flows included in the flowpac:
typo: flowpac should be flowpack

2020-11-25 21:57 UTC, charleschan-okta commented on workflows/contractor_expiry_notification/readme.md
> +Below is a summary of the flows included in the flowpac:
typo: flowpac should be flopack

2020-11-25 21:57 UTC, charleschan-okta commented on workflows/contractor_expiry_notification/workflow.json
> +      "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/contractor-expiry-notification/configurationTableData.csv"
The path is referring to .../contractor-expiry-notification/..., should be .../contractor_expiry_notification/... (ie. using underscore)

2020-11-25 21:57 UTC, charleschan-okta commented on workflows/contractor_expiry_notification/workflow.json
> +      "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/contractor-expiry-notification/readme.md"
The path is referring to .../contractor-expiry-notification/readme.md, should be .../contractor_expiry_notification/readme.md (ie. using underscore)

2020-11-26 02:11 UTC, charleschan-okta approved these changes
1) workflow.json file needs to be updated (using underscore instead of dash for the path)
2) minor typo in readme file
3) u probably want to remove all the files that are still using dash in the path to avoid confusion. If these are merged, they can also show up in the catalog

2020-12-03 19:49 UTC, closed without merging

2020-12-03 19:50 UTC, davidroossien-okta commented
closed because we merged a different PR