New Template for G Suite + HTTP
okta/workflows-templates pull request #51
Opened 2021-01-08 19:40 UTC by arvilnagpal-okta

@charleschan-okta @davidroossien-okta Could you guys please review and approve?

@richardheng-okta fyi

2021-01-12 00:29 UTC, charleschan-okta requested changes
Some issues w/ the readme and workflow.json files

2021-01-12 00:29 UTC, charleschan-okta commented on workflows/raw_http_connection_gsuite-main/workflow.json
> +   "name": "raw_http_connection_gsuite",
The folder name is: raw_http_connection_gsuite-main, which does not conform to the rule:
1. Folder name needs to be lower case and separated with underscore

Do u wanna use: "raw_http_connection_gsuite-main" or " raw_http_connection_gsuite"?
If u use the latter, the folder name and workflow name would match then

2021-01-12 00:29 UTC, charleschan-okta commented on workflows/raw_http_connection_gsuite-main/workflow.json
> +      "okta"
There is no "okta" connector used in the flow

2021-01-12 00:29 UTC, charleschan-okta commented on workflows/raw_http_connection_gsuite-main/workflow.json
> +         "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/raw_http_connection_gsuite/readme.md"
Pl make sure the path here match the folder path

2021-01-28 22:28 UTC, sscode52 commented on workflows/raw_http_connection_gsuite-main/readme.md
> +1. Navigate to[ https://console.developers.google.com/](https://console.developers.google.com/) and login with the G Suite Admin login.
You would need Super Admin permissions in Gsuite to get the required scopes and run the flows.

2021-01-28 22:29 UTC, sscode52 commented on workflows/raw_http_connection_gsuite-main/workflow.json
> +         "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/raw_http_connection_gsuite/readme.md"
This should match in the new PR #58

2021-02-22 00:46 UTC, charleschan-okta commented
Arvil created this PR but it’s superceded by PR#58 by Sowmya. So close this PR

2021-02-22 00:46 UTC, closed without merging