manage_gsuite_user_licenses template review | OKTA-343758
okta/workflows-templates pull request #54
Opened 2021-01-22 15:51 UTC by oleksandrkysil-okta

Jira Ticket: https://oktainc.atlassian.net/browse/OKTA-343758
Changes: 
- Reviewed readme.md file
- Reviewed workflow.json file

2021-01-28 06:33 UTC, charleschan-okta requested changes
1) readme.md needs to have some steps removed (applicable to import/export flopack file ony)
2) pl update workflow.json description accordingly
3) Other minor nits

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +    * Change the User Name field to match the email address of your existing G Suite manager user. (The user that receives the email messages about the target user`s licenses being removed or added.)
...about the target user's (ie. not `)

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +    * **Delay in Minutes**: The increment of time as specified by the Delay Interval in minutes that will transpire between the time the user`s G Suite account is disabled and the user`s G Suite lice
...time the user's (ie. not `)

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +12. Now we will reset the user`s G Suite status. Put that same user back in the Okta specified group.
...reset the user's (ie. not `)

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +* The user`s G Suite account will be disabled immediately.
... the user's (ie. not `)

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +9. If you return to the G Suite Admin Portal and refresh the page, then select that user, you`ll see that user has been suspended by admin, but the user still has and G Suite License assigned.
1) you'll (not you`ll)

2) but the user still has and G Suite License assigned
should be: but the user still has **an** G Suite License assigned

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +5. Navigate to the G Suite Flows folder.
Steps 1 to 5 are not needed anymore because when the user pick and install the template from the "Templates" Page, it will automatically create a new folder and install the template there (with all the flows and tables available).

Steps 1 to 5 are used only if u have a flopack file (of which the mechanism is used before "Template" Page and flow discovery catalog is available)

2021-01-28 06:33 UTC, charleschan-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +13. The manager will get an email that the users G Suite user has been enabled and license restored.
The manager will get an email that the user's G Suite user has been enabled and license restored. (ie. the user's)

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/workflow.json
> +  "description": "This workflow will demonstrate the ability to disable a user in G Suite and then after a specified delay removes the assigned G Suite licenses.  Another part of the workflow will re
Fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +    * Change the User Name field to match the email address of your existing G Suite manager user. (The user that receives the email messages about the target user`s licenses being removed or added.)
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +    * **Delay in Minutes**: The increment of time as specified by the Delay Interval in minutes that will transpire between the time the user`s G Suite account is disabled and the user`s G Suite lice
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +12. Now we will reset the user`s G Suite status. Put that same user back in the Okta specified group.
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +* The user`s G Suite account will be disabled immediately.
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +9. If you return to the G Suite Admin Portal and refresh the page, then select that user, you`ll see that user has been suspended by admin, but the user still has and G Suite License assigned.
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +5. Navigate to the G Suite Flows folder.
fixed

2021-02-22 12:19 UTC, oleksandrkysil-okta commented on workflows/manage_gsuite_user_licenses/readme.md
> +13. The manager will get an email that the users G Suite user has been enabled and license restored.
fixed

2021-02-22 15:14 UTC, charleschan-okta approved these changes
LGTM 🚀

2021-02-23 16:28 UTC, closed without merging