Raw HTTP Gsuite Connector Edited
okta/workflows-templates pull request #58
Opened 2021-01-28 22:27 UTC by sscode52

Incorporated changes from the previous PR for the same connector #51

2021-01-29 00:30 UTC, charleschan-okta requested changes
Please add "googledirectory" connectior

2021-01-29 00:30 UTC, charleschan-okta commented on workflows/raw_http_connection_gsuite/workflow.json
> +   "description": "Our current Workflows connector for Gsuite Admin does not include all functions within Google Workspace. The Custom API card is also restricted to the Directory and Licensing APIs.
Actually Google Workspace app is used in the flow, so pl add:
  "connectors": [
    "googledirectory"
  ],

2021-01-29 19:46 UTC, sscode52 commented on workflows/raw_http_connection_gsuite/workflow.json
> +   "description": "Our current Workflows connector for Gsuite Admin does not include all functions within Google Workspace. The Custom API card is also restricted to the Directory and Licensing APIs.
I've updated this

2021-02-02 21:07 UTC, charleschan-okta approved these changes
LGTM 🚀

2021-02-23 20:26 UTC, merged