Template reassign_files_while_deprovisioning_with_box | OKTA-343761
okta/workflows-templates pull request #66
Opened 2021-03-02 16:09 UTC by oleksandrkysil-okta

Jira Ticket:
- https://oktainc.atlassian.net/browse/OKTA-343761

Description:
- Reviewed reassign_files_while_deprovisioning_with_box template

2021-03-04 04:22 UTC, davidroossien-okta requested changes
@oleksandrkysil-okta  please replace readme.md with this file, which has various grammatical changes.

[readme.txt](https://github.com/okta/workflows-templates/files/6080818/readme.txt)

2021-03-04 04:22 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/workflow.json
> +  "description": "The purpose of this template is to automatically create Box account for a user and a folder for them or transfer a target user’s Box files and folders to that target user’s manager
The purpose of this template is to automatically create a Box account for a user, a folder and send a notification email to the user's manager. It transfers a user’s Box files and folders to a manager if user was removed from a specific okta group.

2021-03-04 13:48 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/workflow.json
> +  "description": "The purpose of this template is to automatically create Box account for a user and a folder for them or transfer a target user’s Box files and folders to that target user’s manager
Thanks. Fixed that.

2021-03-05 14:13 UTC, oleksandrkysil-okta commented
> @oleksandrkysil-okta please replace readme.md with this file, which has various grammatical changes.
> 
> [readme.txt](https://github.com/okta/workflows-templates/files/6080818/readme.txt)

Did that

2021-03-16 15:49 UTC, davidroossien-okta requested changes

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +* If you do not choose to federate your [Box](http://Box.com) tenant with Okta, you will need to configure a [Box](http://Box.com) application in your Okta tenant that has Okta Workflows enabled conf
enabled and configured

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +1. In Workflows find the [Templates] button at the top of the page an click on it.
and click

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +5. Select the Okta Box User - Deprovision Flow Flow from the folder.
extra Flow?

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +9. Navigate back to the workflows in the flow pack.
There is no flow pack. Should it say "Navigate back to the worksflows in the template."?

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +## Testing this Flow
these Flows

2021-03-16 15:49 UTC, davidroossien-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +    If [Box](http://Box.com) is federated to Okta, login to Okta as the manager and click on the [Box](http://Box.com) chicklet to Single Sign On into Box.
chiclet

https://help.okta.com/en/prod/Content/Topics/Reference/glossary.htm

2021-03-18 14:26 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +## Testing this Flow
Fixed that

2021-03-18 14:26 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +* If you do not choose to federate your [Box](http://Box.com) tenant with Okta, you will need to configure a [Box](http://Box.com) application in your Okta tenant that has Okta Workflows enabled conf
FIxed that

2021-03-18 14:26 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +1. In Workflows find the [Templates] button at the top of the page an click on it.
FIxed that

2021-03-18 14:27 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +5. Select the Okta Box User - Deprovision Flow Flow from the folder.
FIxed that

2021-03-18 14:27 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +9. Navigate back to the workflows in the flow pack.
FIxed that

2021-03-18 14:27 UTC, oleksandrkysil-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +    If [Box](http://Box.com) is federated to Okta, login to Okta as the manager and click on the [Box](http://Box.com) chicklet to Single Sign On into Box.
FIxed that
Thanks for the link!

2021-03-18 14:42 UTC, davidroossien-okta approved these changes

2021-03-18 21:20 UTC, merged

2021-03-26 22:45 UTC, markmoussa-okta commented on workflows/reassign_files_while_deprovisioning_with_box/workflow.json
> +  "description": "The purpose of this template is to automatically create a Box account for a user, a folder and send a notification email to the user's manager. It transfers a user’s Box files and f
This template creates a Box account for a user, creates a folder, and sends a notification email to the user's manager. The flow also transfers a user's Box files and folders to a manager if the user is removed from a specific Okta group.

2021-03-26 22:46 UTC, markmoussa-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +For ths template to work you will need:
Remove this sentence

2021-03-26 22:48 UTC, markmoussa-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +* An Okta Workflows connector in to your Okta tenant that has Workflows enabled.
In your Okta tenant, Workflows must be enabled, and a connection for the Okta connector.

2021-03-26 22:49 UTC, markmoussa-okta commented on workflows/reassign_files_while_deprovisioning_with_box/readme.md
> +## Testing this Flow
Generally @oleksandrkysil-okta , we are going now with lower case "flow" and "flows" instead of treating it as a proper noun "Flow" or "Flows". Please make a global change to use "flow" and "flows". We will soon start doing so for all content on help.okta.com