New User Registration Template | OKTA-377085
okta/workflows-templates pull request #73
Opened 2021-03-19 14:11 UTC by oleksandrkysil-okta

Jira ticket:
- https://oktainc.atlassian.net/browse/OKTA-377085

Description:
- New template review

Note:
- It Pending for a youtube video link in the workflows.json file, but the doc files can be reviewed without that.

2021-03-25 02:07 UTC, davidroossien-okta requested changes

2021-03-25 02:07 UTC, davidroossien-okta commented on workflows/new_user_registration/readme.md
> +    1. Make sure a connection is selected for the instance of the “HTTP | Raw Request” card. This card is used to link to the external preference management system.
"to a mock external preference management system."

2021-03-25 02:07 UTC, davidroossien-okta commented on workflows/new_user_registration/readme.md
> +    1. Make sure a connection is selected for the instance of the “HTTP | Raw Request” card. This card is used to link to the external preference management system.
"to a mock external preference management system."

2021-03-25 02:07 UTC, davidroossien-okta commented on workflows/new_user_registration/workflow.json
> +      "destination": ""
missing link

2021-03-26 05:59 UTC, markmoussa-okta reviewed
@davidroossien-okta I added some edits to both the summary in the workflow.json and the introductory content in readme. I'll ping you offline to streamline the review process for all such non-InfoDev-sourced documentation.

2021-03-26 06:03 UTC, markmoussa-okta commented on workflows/new_user_registration/readme.md
> +In this template, the context of new user registration is processed by Workflows which shall customize the branding, customize the birthright enablement, and link to external systems for duplication
@davidroossien-okta Beats me. What about "Preference Management" - is that a proper noun? There's some oddities here that I need to clear up with you.

2021-03-26 14:56 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/workflow.json
> +  "description": "In CIAM use cases, many business units, locales, and brands may require distinct user management operations. Okta Workflows can help implement custom processing of the registration
Updated

2021-03-26 14:56 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +In CIAM use cases, many business units, locales, and brands may require distinct user management operations. Okta Workflows can help implement custom processing of the registration context.
This was removed, so no need in changes

2021-03-26 14:56 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +## Before you get Started / Prerequisites
removed

2021-03-26 14:57 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +## Testing this Flow
Changed

2021-03-26 14:57 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +*   None
Changed

2021-03-26 14:57 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +   1. Make sure a connection is selected for the instance of the “HTTP | Raw Request” card. This card is used to link to an external duplicate user check.
Fixed

2021-03-26 14:57 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/readme.md
> +    1. Make sure a connection is selected for the instance of the “HTTP | Raw Request” card. This card is used to link to the external preference management system.
Fixed

2021-03-26 14:57 UTC, oleksandrkysil-okta commented on workflows/new_user_registration/workflow.json
> +      "destination": ""
was added

2021-03-30 21:32 UTC, davidroossien-okta approved these changes

2021-03-30 21:34 UTC, merged