Remote Sync | tenplate | OKTA-377504
okta/workflows-templates pull request #74
Opened 2021-03-22 11:21 UTC by oleksandrkysil-okta

Jira ticket:
- https://oktainc.atlassian.net/browse/OKTA-377504

Description:
- Reviewed template

Note:
- Currently without youtube video link, but the readme file can be reviewed.

2021-03-25 00:52 UTC, charleschan-okta requested changes

2021-03-25 00:52 UTC, charleschan-okta commented on workflows/remote_sync/readme.md
> +When the identity information sourced in Okta changes these users and attributes need to be synchronized downstream. Okta Workflows provides an easy to implement, a fully customizable method to updat
wording: Okta Workflows provides an easy to implement and fully customizable method

2021-03-25 00:52 UTC, charleschan-okta commented on workflows/remote_sync/readme.md
> +    * Make sure a connection is selected for the instances of the “Okta” cards.If it was not selected automatically, select the necessary connection manually.
Suggestion: For items 2, 3, and 4, can be more succinct:
For "Event Update User of Group", "Event Remove user From Group", and "Event Add user to Group", Make sure a connection is selected for the instances of the “Okta” cards. If it was not selected automatically, select the necessary connection manually.

2021-03-25 00:52 UTC, charleschan-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
Same suggestion here to be more succinct

2021-03-25 00:52 UTC, charleschan-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems can be decommissioned. When the identity information sourced in Okta changes these attr
wording: Okta Workflows provides an easy to implement and fully customizable method

2021-03-26 06:22 UTC, markmoussa-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems can be decommissioned. When the identity information sourced in Okta changes these attr
@oleksandrkysil-okta 
Please replace the description with this edited version:
Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attributes need to be synchronized downstream. This template provides an easy-to-implement, fully customizable method to update a remote system with CRUD (create, update and delete) operations.

2021-03-26 06:23 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +When the identity information sourced in Okta changes these users and attributes need to be synchronized downstream. Okta Workflows provides an easy to implement, a fully customizable method to updat
@oleksandrkysil-okta 
Please replace the summary in the Overview section with this edited version:
Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attributes need to be synchronized downstream. This template provides an easy-to-implement, fully customizable method to update a remote system with CRUD (create, update and delete) operations.

2021-03-26 06:24 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +Before you get started, here are the things you’ll need:
Remove "Before you get started, here are the things you’ll need:"

2021-03-26 06:25 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +*   Access to an Okta tenant with Okta Workflows enabled for your Org
lower case "org"

2021-03-26 06:27 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +*   The Remote System API calls in this sample are using a mock API. Create HTTP Connector for mock API Auth = none
Replace the second sentence with:
"Create an HTTP connector with the Auth for the mock API as none."

2021-03-26 06:27 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +    * Okta Workflow HTTP Connections securely enable;
Enable secure HTTP connections:

2021-03-26 06:29 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +    * Make sure a connection is selected for the instances of the “Okta” cards.If it was not selected automatically, select the necessary connection manually.
Agree with Charles. Rewrite as follows:
For the following flows, make sure a connection is selected for the instances of the Okta connector cards:

- Event Update User of Group
- Event Remove User from Group
- Event Add User to Group

If the connection is not selected automatically, select the necessary connection manually.

2021-03-26 06:30 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +    * Make sure a connection is selected for the instances of the “Okta” cards.If it was not selected automatically, select the necessary connection manually.
Note that the flows should be renamed (capitalization-wise) as I suggest in my previous comment.

2021-03-26 06:30 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
...an appropriate HTTP connector...

2021-03-26 06:31 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
...an appropriate HTTP connector...

2021-03-26 06:31 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +8. Create Okta Group named "API Provisioning Group"
Create an Okta group named...

2021-03-26 06:32 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +9. Add custom attribute to Okta User Profile name = 'customId' type=string
Add a custom attribute to the Okta user profile...

2021-03-26 06:32 UTC, markmoussa-okta commented on workflows/remote_sync/readme.md
> +   * This attribute shall hold user Id from Remote System
This attribute will contain the user ID from...

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +When the identity information sourced in Okta changes these users and attributes need to be synchronized downstream. Okta Workflows provides an easy to implement, a fully customizable method to updat
Did that, thanks

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +    * Make sure a connection is selected for the instances of the “Okta” cards.If it was not selected automatically, select the necessary connection manually.
Updated

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
did that

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems can be decommissioned. When the identity information sourced in Okta changes these attr
fixed

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +Before you get started, here are the things you’ll need:
removed

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +*   Access to an Okta tenant with Okta Workflows enabled for your Org
added

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +*   The Remote System API calls in this sample are using a mock API. Create HTTP Connector for mock API Auth = none
replaced

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +    * Okta Workflow HTTP Connections securely enable;
changed

2021-03-26 14:21 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
changed

2021-03-26 14:22 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +   * Select appropriate HTTP Connector for "HTTP Raw Request" card
changed

2021-03-26 14:22 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +8. Create Okta Group named "API Provisioning Group"
fixed

2021-03-26 14:22 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +9. Add custom attribute to Okta User Profile name = 'customId' type=string
changed

2021-03-26 14:22 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +   * This attribute shall hold user Id from Remote System
changed

2021-03-29 05:41 UTC, davidroossien-okta requested changes

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attrib
(create, read, update and delete)

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attrib
replace CIAM with "customer identify and access management"

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attributes need to be sy
replace CIAM with "customer identify and access management"

(create, read, update and delete)

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +## Before you get Started / Prerequisites
Remove "Before you get Started /"

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +1. Configure a HTTP Connector to communicate with a remote system
should it be "Configure all the HTTP Connector cards"? 

which kind of card(s) are used in the flows? i.e. PUT, POST, DELETE? or CALL?

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +## Testing this Flow
"Testing these Flows"

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +The easiest way to test a flow is to add your test user to the Okta Group "API Provisioning Group"
test these flows

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +1. In the Okta Admin UI, navigate to the test users page.
user's

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +4. In the Profile tab of the Users page, edit the value for "city" attribute.
user's

2021-03-29 05:41 UTC, davidroossien-okta commented on workflows/remote_sync/readme.md
> +5. Inspect the remote system for change in test users' "city" value.
user's

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +1. Configure a HTTP Connector to communicate with a remote system
Raw Request

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attrib
Updated

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/workflow.json
> +  "description": "Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attrib
replaced

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +Many CIAM customers have multiple user stores that need to be maintained until legacy systems are decommissioned. When the identity information sourced in Okta changes, these attributes need to be sy
replaced

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +## Before you get Started / Prerequisites
removed

2021-03-30 16:43 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +## Testing this Flow
updated

2021-03-30 16:44 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +The easiest way to test a flow is to add your test user to the Okta Group "API Provisioning Group"
updated

2021-03-30 16:44 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +1. In the Okta Admin UI, navigate to the test users page.
updated

2021-03-30 16:44 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +4. In the Profile tab of the Users page, edit the value for "city" attribute.
fixed

2021-03-30 16:44 UTC, oleksandrkysil-okta commented on workflows/remote_sync/readme.md
> +5. Inspect the remote system for change in test users' "city" value.
fixed

2021-03-31 01:54 UTC, davidroossien-okta approved these changes

2021-03-31 02:03 UTC, merged