OnFido Create Applicant | Template Review | OKTA-380518
okta/workflows-templates pull request #75
Opened 2021-03-23 13:32 UTC by oleksandrkysil-okta

Jira ticket:
- https://oktainc.atlassian.net/browse/OKTA-380518
Description:
- Template Review
Note:
- There is no youtube video link, but readme file could be checked without it.

2021-03-26 22:26 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/workflow.json
> +  "description": "Using the Okta User Created Event, this workflow will create an Onfido Applicant and save the applicant ID into the user's profile in Okta.",
Please replace the description with the following edited version:

With the User Created event card for the Okta connector, this flow creates an Onfido applicant and saves the applicant ID in the user’s Okta profile.

2021-03-26 22:29 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +This workflow creates an Onfido applicant from the Okta Create User event for use in Identity Verification. The Okta user profile is updated with the Onfido Applicant ID.
Please replace this opening paragraph with the following:

For identity verification, this flow creates an Onfido applicant using a User Created event card for the Okta connector and saves the applicant ID in the user’s Okta profile.

2021-03-26 22:32 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +Creating an applicant in Onfido at Okta user creation allows organizations to ensure that each newly registering user has an Onfido Applicant ID that can be used for Identity Verification Checks. Thi
Please replace this paragraph with the following:

When you create an application in Onfido as part of the Okta user creation process, your organization ensures that each newly registered user has an Onside application ID that can be used for identity verification checks. This applicant ID can be reused for other Onfido features such as facial biometric re-checks, initializing the Onfido SDK, and collecting report information for a check on a specific user.

2021-03-26 22:32 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +Before you get started, you will need:
Remove this sentence

2021-03-26 22:33 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +* OnFido applicants are created for all Okta Users that are created. Additional conditional logic can be added in the workflow to create OnFido applicants based on user status, group membership, etc.
replace "workflow" with "flow"

2021-03-26 22:34 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +* Keep in mind the [Okta Workflows System Limits](https://help.okta.com/en/prod/Content/Topics/Workflows/workflows-system-limits.htm) of Event Hook and Okta API rate limits.
Replace with:

Refer to the [Okta Workflows System Limits](https://help.okta.com/en/prod/Content/Topics/Workflows/workflows-system-limits.htm) for event hooks and Okta API rate limits.

2021-03-26 22:34 UTC, markmoussa-okta commented on workflows/onfido_create_applicant/readme.md
> +* Onfido also has rate limits for API calls: [Onfido Rate Limit](https://documentation.onfido.com/#rate-limits) that should be taken into account when designing workflows.
replace "workflows" with "flows"

2021-03-29 05:57 UTC, davidroossien-okta requested changes

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Before you get Started / Prerequisites
Remove "Before you get Started /"

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +## Onfido Create Applicant
@oleksandrkysil-okta I think we want a single # here, and then please adjust all other sections.

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Before you get Started / Prerequisites
I think we want ## not ###

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Overview
I think we want ## not ###

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Setup Steps
I think we want ## not ###

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Testing this Flow
I think we want ## not ###

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Limitations & Known Issues
I think we want ## not ###

2021-03-29 05:57 UTC, davidroossien-okta commented on workflows/onfido_create_applicant/readme.md
> +### Limitations & Known Issues
I think we want ## not ###

2021-03-30 16:29 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +This workflow creates an Onfido applicant from the Okta Create User event for use in Identity Verification. The Okta user profile is updated with the Onfido Applicant ID.
replaced

2021-03-30 16:29 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +Creating an applicant in Onfido at Okta user creation allows organizations to ensure that each newly registering user has an Onfido Applicant ID that can be used for Identity Verification Checks. Thi
updated

2021-03-30 16:29 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +Before you get started, you will need:
removed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +* OnFido applicants are created for all Okta Users that are created. Additional conditional logic can be added in the workflow to create OnFido applicants based on user status, group membership, etc.
replaced

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +* Keep in mind the [Okta Workflows System Limits](https://help.okta.com/en/prod/Content/Topics/Workflows/workflows-system-limits.htm) of Event Hook and Okta API rate limits.
replaced

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Before you get Started / Prerequisites
removed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +## Onfido Create Applicant
changed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Before you get Started / Prerequisites
changed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Overview
changed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Setup Steps
changed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Testing this Flow
changed

2021-03-30 16:30 UTC, oleksandrkysil-okta commented on workflows/onfido_create_applicant/readme.md
> +### Limitations & Known Issues
changed

2021-03-31 02:56 UTC, davidroossien-okta approved these changes

2021-03-31 03:03 UTC, merged