Make titles consistent in Designer UI and Github | OKTA-352557
okta/workflows-templates pull request #78
Opened 2021-04-28 12:38 UTC by oleksandrkysil-okta

Jira Ticket:
- https://oktainc.atlassian.net/browse/OKTA-352557
Changes:
- Fix titles that users see in Designer (Trex and Prod)
- Fix workflows files
- some fixes in readmes

2021-04-29 04:18 UTC, davidroossien-okta requested changes
I committed some changes directly to your branch.

1. we don't want : after titles.
2. I improved spacing
3. I added numbering to many files with lists.

I think you may have missed 

create_report_on_okta_events

You should have modified 28 different files, but I only see 22 of them. Could you find the missing 6 files and make those changes?

2021-04-30 13:28 UTC, oleksandrkysil-okta commented
> I committed some changes directly to your branch.
> 
> 1. we don't want : after titles.
> 2. I improved spacing
> 3. I added numbering to many files with lists.
> 
> I think you may have missed
> 
> create_report_on_okta_events
> 
> You should have modified 28 different files, but I only see 22 of them. Could you find the missing 6 files and make those changes?
@davidroossien-okta 
originally I found 27 requests for changes, here is the list with expected filies changes:

1. assign_temporary_group_memberships / workflow.json
2. notify_user_on_profile_update / workflow.json
3. onboard_and_offboard_with_office365 / workflow.json
4. create_report_google_sheets / workflow.json
5. googledrive_file_transfer / workflow.json
6. intro_custom_api_actions / workflow.json
7. make_api_requests_http_card / workflow.json
8. manage_group_members_using_profile_attributes / workflow.json
9. servicenow_approvals / workflow.json
10. assign_temporary_group_memberships / readme.md
11. generate_unique_username / readme.md
12. googledrive_file_transfer / readme.md
13. notify_user_on_profile_update / readme.md
14. office365_create_guest_users / readme.md
15. send_sms_via_twillio / readme.md
16.  reassign_files_while_deprovisioning_with_box / readme.md x 2
17. servicenow_approvals / readme.md
18. contractor_expiry_notification /  readme.md
19. make_api_requests_http_card / readme.md
20. manage_aws_sso_entitlements / readme.md
21.  manage_group_members_using_profile_attributes / readme.md
22. manage_gsuite_user_licenses / readme.md
23. onboard_and_offboard_with_office365 / readme.md
24. create_report_on_okta_events / readme.md
25. generate_unique_emails / readme.md
26. import_users_google_sheets / readme.md

after rereview i found that these templates were really missed by me:
- create_report_on_okta_events
- generate_unique_emails
- office365_create_quest_users
- send_sms_via_twilio

and for this template there were 2 changes in 1 file: reassign_files_while_deprovisioning_with_box
@davidroossien-okta 
i review all files and found some more issues to fix

2021-05-20 23:10 UTC, davidroossien-okta approved these changes

2021-05-20 23:19 UTC, davidroossien-okta requested changes
I committed several changes directly to the branch, so please be careful not to lose them.

The build failed due to a capitalized README.md

"File workflows/initiate_flow_with_api_endpoint/readme.md not found. This file is needed while adding workflow template."

2021-05-25 15:20 UTC, davidroossien-okta approved these changes

2021-05-25 15:20 UTC, merged