Fix readme file for Reference an on-premise LDAP Mulesoft template
okta/workflows-templates pull request #79
Opened 2021-05-11 14:55 UTC by oleksandrkysil-okta

JIra tickets:
- https://oktainc.atlassian.net/browse/OKTA-381539
- https://oktainc.atlassian.net/browse/OKTA-389946

Link to file with comments:
- https://docs.google.com/document/d/12ZYnm9DtmsskT2VTMpZ9cJ7Qmi5wVn0qSbOGZX0imCY/edit#heading=h.wwrqw5ueiaq6
Description:
- Fix readme file for Reference an on-premise LDAP Mulesoft template

2021-05-18 22:54 UTC, davidroossien-okta approved these changes

2021-05-18 23:13 UTC, davidroossien-okta requested changes
@oleksandrkysil-okta it appears this failed validation because of the dash - in the folder name. Could you change it to "reference_an_on_premise_ldap_mulesoft" ?

2021-05-19 11:59 UTC, oleksandrkysil-okta commented
> @oleksandrkysil-okta it appears this failed validation because of the dash - in the folder name. Could you change it to "reference_an_on_premise_ldap_mulesoft" ?

changed

2021-05-19 15:46 UTC, davidroossien-okta approved these changes

2021-05-19 16:00 UTC, merged

2021-05-19 16:00 UTC, davidroossien-okta commented
Merging even thought the Travis PR check failed. https://travis-ci.com/github/okta/workflows-templates/jobs/506351900

Validation rules need to be expanded to allow for src subfolder.
Created:
https://oktainc.atlassian.net/browse/OKTA-396973